= Power-Annotations

Instead of `SuperHero.class.getAnnotation(Entity.class)`, use `Annotations.on(SuperHero.class).get(Entity.class)` and you'll get some very powerful features described below. This works also for fields and methods; simply use `Annotations.onField` or `Annotations.onMethod`.

== Implemented Features

=== Jandex

If there is a https://github.com/wildfly/jandex[Jandex] index file, all annotations will be read from there. Java reflection will only be used as a fallback if a class is not in the index.

This is purely optional, i.e. if there is no Jandex file, Power-Annotations will fall back to use JDK reflection.


=== Mixins

Say you have a class that you want to but can't add annotations to; maybe it's a class from some library or even from the JDK.
Then you can create your own class (or interface) and annotate it as `@MixinFor` the target class.
The annotations you put on your mixin class will work as if they where on the target class.

Note that the implementation requires a Jandex index file to find the mixins.
And of course this works only for the annotations from frameworks that use Power-Annotations.

== Planned Features

* Stereotypes (basics)
* MP Config to overwrite annotations
* class annotations as fallback for method/field
* package annotations as fallback for classes
* Stereotype property propagation, i.e. stereotype `@Property(name = "foo")` can be expanded to `@JsonbProperty(value = "foo")` (note the `name` -> `value`)


== Open Questions

* How to test without reflection available (and some implementation details using Jandex)?
