= Power-Annotations

Instead of `SuperHero.class.getAnnotation(Entity.class)`, use `Annotations.on(SuperHero.class).get(Entity.class)` and you'll get some very powerful features described below. This works also for fields and methods; simply use `Annotations.onField` or `Annotations.onMethod`.

== Implemented Features

=== Jandex

If there is a https://github.com/wildfly/jandex[Jandex] index file, all annotations will be read from there. Java reflection will only be used as a fallback if a class is not in the index.

This is purely optional, i.e. if there is no Jandex file, Power-Annotations will fall back to use JDK reflection.


=== Mixins

Say you have a class that you want to but can't add annotations to; maybe it's a class from some library or even from the JDK.
Then you can create your own class (or interface) and annotate it as `@MixinFor` the target class.
The annotations you put on your mixin class will work as if they where on the target class.

Note that the implementation requires a Jandex index file to find the mixins.
And of course this works only for the annotations from frameworks that use Power-Annotations.


=== Stereotypes

Just like https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#stereotypes[CDI-Stereotypes], but not restricted to CDI, i.e. the annotations used by any framework that supports Power Annotations can be used with stereotypes. We have our own `Stereotype` class, but as that would exclude CDI, any annotation with that name will work.

The simplest use-case for Stereotypes is aliasing, i.e. using one annotation instead of another, e.g. `@Property` instead of `@JsonbProperty` (assuming your JBON-B implementation supported Power Annotations). And it gets more interesting, when you add more annotations from other (supporting) frameworks to your stereotype, e.g. `@XmlAttribute` from JAX-B.


== Planned Features

* MP Config to overwrite annotations
* class annotations as fallback for method/field
* package annotations as fallback for classes
* Stereotype property propagation, i.e. stereotype `@Property(name = "foo")` can be expanded to `@JsonbProperty(value = "foo")` (note the `name` -> `value`)


== Open Questions

* How to test without reflection available? (and some implementation details using Jandex)
* We may need to overwrite repeatable annotations instead of merging them. Maybe this should be an option on the Annotations API or another meta-annotation.
